### ISSUE TITLE
ปรับความยากของเกม

### ISSUE THREAD

**Issue by orlyomyim** [JengPN/cpe103-test-group-13#11]
waveที่2 ไวรัสอึดมากตัวใหญ่เเละมีจำนวนมาก พื้นที่ของเกมค่อนข้างเเคบทำให้เกมเล่นยากจนเกินไปจึงอยากให้ปรับขนาดของไวรัสwave2ให้มีขนาดเล็กลงเพื่อให้มีพื้นที่ซ่อนมากขึ้น

**Comment by JengPN** [comment]
Wave2 ต้องลดจำนวนตัวไวรัสให้น้อยลง

**Comment by ChayathonPP** [comment]
https://scratch.mit.edu/projects/731344119

**Comment by orlyomyim** [comment]
https://scratch.mit.edu/projects/734606140
