### ISSUE TITLE
เพิ่มฉากก่อนเข้าเกม

### ISSUE THREAD

**Issue by orlyomyim** [JengPN/cpe103-test-group-13#13]
เมนูก่อนเข้าเกม

**Comment by orlyomyim** [comment]
![image](https://user-images.githubusercontent.com/110971184/189953284-7d7a0541-6d55-4f76-ad8a-c8ab7cb0271d.png)

ประมาณนี้

**Comment by JengPN** [comment]
![หน้าปก](https://user-images.githubusercontent.com/110963174/189955239-a1745bae-cd2e-4b26-af89-92bc6879dc47.jpg)
