### ISSUE TITLE
designตัวละครในเกม

### ISSUE THREAD

**Issue by orlyomyim** [JengPN/cpe103-test-group-13#18]
-ตัวละครหลัก(ตัวเรา)
-ไวรัส
-อนิเมชั่น

**Comment by JWJY** [comment]
![image](https://user-images.githubusercontent.com/110969308/190067826-5d25bea2-dae4-4770-ad7a-7813073e3f68.png)
![image](https://user-images.githubusercontent.com/110969308/190067805-41380929-993f-41db-9390-fde6502245ed.png)
![image](https://user-images.githubusercontent.com/110969308/190067812-a299ba7c-614d-4667-abb2-a49b2e7f9cf1.png)
![Uploading image.png…]()

**Comment by JengPN** [comment]
![illustration-de-style-dessin-cibler-médiéval-d-archer-le-guerrier-avec-un-tir-à-l-arc-vise-son-sur-vecteur-coloré-champ-181743593](https://user-images.githubusercontent.com/110963174/190087334-bc0e323e-e61c-4baf-a417-185c51aec2f6.jpg)
![1f990c1975438f6030bff1f0c4e4074a](https://user-images.githubusercontent.com/110963174/190087339-83146d5c-15ea-4195-9be0-09b9e629df39.jpg)
![5988 png_860](https://user-images.githubusercontent.com/110963174/190087342-042f514e-a577-426c-b581-5480133de710.png)
![20160121180750_31873](https://user-images.githubusercontent.com/110963174/190087343-e9ceaea7-61dc-4b34-b7b2-80da7730be6d.jpg)

**Comment by JengPN** [comment]
![image](https://user-images.githubusercontent.com/110963174/190131634-8ecaffdd-72be-4044-a68c-925b04693f5d.png)

![image](https://user-images.githubusercontent.com/110963174/190131685-9c3b55d9-3623-4a37-9dbc-e62e3d769e03.png)

![image](https://user-images.githubusercontent.com/110963174/190131745-f607089b-96a1-4f9c-b57b-64937fad1f53.png)

![image](https://user-images.githubusercontent.com/110963174/190131756-a41d3938-6477-44e3-9964-61fc3f1b6ac8.png)

**Comment by JengPN** [comment]
![image](https://user-images.githubusercontent.com/110963174/190208935-b5b4eb39-ac8e-43a7-aff2-8a543007e711.png)

![image](https://user-images.githubusercontent.com/110963174/190208958-74c7512e-0ece-4b84-b8a2-22c1171e6c32.png)

![image](https://user-images.githubusercontent.com/110963174/190208975-3ccf7753-245c-4588-872a-f8372a2fcc0e.png)

![image](https://user-images.githubusercontent.com/110963174/190208985-19116343-ceec-4c29-8b37-968def7e9cd3.png)

![image](https://user-images.githubusercontent.com/110963174/190209012-93752e87-d0db-42d4-a6e3-a997b5817e6d.png)

![image](https://user-images.githubusercontent.com/110963174/190209026-51f2d0d1-6e38-402a-a374-fe0acbd99efe.png)

![image](https://user-images.githubusercontent.com/110963174/190209053-0e3e9e62-5289-4e18-acfb-63e1b19ced77.png)
