### ISSUE TITLE
เพิ่มข้อมูล การเปลี่ยนด่าน นับคะแนน เปลี่ยนฉากหลัง

### ISSUE THREAD

**Issue by JengPN** [JengPN/cpe103-test-group-13#20]

**Comment by JengPN** [comment]
1.อยากให้มีเมนูการเปลี่ยนด่าน เช่น ถ้าไปด่าน2 แล้วอยากให้มีเมนูขึ้นข้างบนว่าด่านที่เท่าไหร่แล้ว
2.เพิ่มเมนูนับคะแนน
3.เปลี่ยนฉากหลังไปตามด่าน
4.เพิ่มหน้าการเก็บคะแนน
5.สกิลแต่ละตัวละคร
6.การแข่งขันจับเวลา
7.วิธีการเล่น

**Comment by JWJY** [comment]
![S__3317762](https://user-images.githubusercontent.com/110969308/190901156-d21f5a1d-4c33-41ea-aa1f-2cccaf88153a.jpg)
![S__3317764](https://user-images.githubusercontent.com/110969308/190901159-8843b242-353f-410a-bd01-272cd0de3a88.jpg)
![S__3317765](https://user-images.githubusercontent.com/110969308/190901160-6d7ad413-ebeb-4009-a59f-2a9a62ca5ec0.jpg)
![S__3317766](https://user-images.githubusercontent.com/110969308/190901166-2b41596a-03a1-4109-9916-2158a5198fd2.jpg)
![S__3317767](https://user-images.githubusercontent.com/110969308/190901167-08d0ef6d-bcba-49bb-8af0-21db068a9b89.jpg)
![S__3317768](https://user-images.githubusercontent.com/110969308/190901168-acbb621b-3b4e-4c6e-b63a-bec01b62c0e7.jpg)

**Comment by orlyomyim** [comment]
https://scratch.mit.edu/projects/734606140
