### ISSUE TITLE
หน้าก่อนเข้าเกม หน้ารวมคะแนน ฉากหลัง

### ISSUE THREAD

**Issue by JengPN** [JengPN/cpe103-test-group-13#21]

**Comment by JengPN** [comment]
![score](https://user-images.githubusercontent.com/110963174/190093056-beeb17a6-fc37-4d61-8a34-0e93570a160c.jpg)

**Comment by JengPN** [comment]
![เลือกตัวละคร](https://user-images.githubusercontent.com/110963174/190093599-c13c8a97-cfd4-4e37-a279-18311f340a99.jpg)

**Comment by orlyomyim** [comment]
https://scratch.mit.edu/projects/734606140
