### ISSUE TITLE
how to play

### ISSUE THREAD

**Issue by orlyomyim** [JengPN/cpe103-test-group-13#23]

**Comment by JengPN** [comment]
![HOW TO PLAY1](https://user-images.githubusercontent.com/110963174/191413806-f3298351-007b-406b-b439-8abce8d273ae.jpg)
![HOW TO PLAY2](https://user-images.githubusercontent.com/110963174/191413809-fbe60b88-ea6a-492f-ab98-6711041b58cb.jpg)
![HOW TO PLAY3](https://user-images.githubusercontent.com/110963174/191413811-0ece8167-7d5c-4047-9f8d-73d58938ebe7.jpg)

**Comment by ChayathonPP** [comment]
https://scratch.mit.edu/projects/734777293
